In [1]:
import tensorflow as tf
from my_tf_utils import * 

# About `tf.unstack`

- Unpacks the given dimension of a rank-R tensor into rank-(R-1) tensors.
- `tf.unstack` gathers tensor by the given axis.
- `tf.unstack(x, axis=n)` returns a `list` that has `x.shape[n]` elements.

# Make a computational graph.

In [2]:
x = tf.Variable([[2,3,4],
                 [5,6,7]], name='x')

In [3]:
unstacked_x_axis0 = tf.unstack(x, axis=0)
unstacked_x_axis1 = tf.unstack(x, axis=1)

# Get the shape of each node.

In [4]:
get_shape(x)

array([2, 3], dtype=int32)

In [5]:
get_shape(unstacked_x_axis0)

array([2, 3], dtype=int32)

In [6]:
get_shape(unstacked_x_axis1)

array([3, 2], dtype=int32)

# Get the value and type of each node.

In [7]:
get_value(x)

array([[2, 3, 4],
       [5, 6, 7]], dtype=int32)

In [8]:
type(get_value(x))

numpy.ndarray

In [9]:
get_value(unstacked_x_axis0)

[array([2, 3, 4], dtype=int32), array([5, 6, 7], dtype=int32)]

In [10]:
type(get_value(unstacked_x_axis0))

list

In [11]:
get_value(unstacked_x_axis1)

[array([2, 5], dtype=int32),
 array([3, 6], dtype=int32),
 array([4, 7], dtype=int32)]

In [12]:
type(get_value(unstacked_x_axis1))

list